Dev
VladmimirShtefan/Lesson_12_Home_work pull request #1
Opened 2022-06-17 13:49 UTC by VladmimirShtefan

For checking

2022-06-18 16:33 UTC, painassasin requested changes

2022-06-18 16:33 UTC, painassasin commented on app.py
> +app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or 'SuperSecretKey'
environ - это словарь, соответственно get работает как у словаря, а значит нужно было написать:
```python
os.environ.get('SECRET_KEY', 'SuperSecretKey')
```

2022-06-18 16:33 UTC, painassasin commented on classes.py
> +        file_extension: str = self.picture.filename.split('.')[-1]
Проверка через расширение - не плохой вариант, но можно загрузить файл с измененным расширением (например у файла pdf заменить расширение на .jpg и твоя проверка пройдет)
Поэтому хорошим вариантом было бы  проверять mimetype у объекта FileStorage

2022-06-18 16:33 UTC, painassasin commented on loader/templates/post_form.html
> +    <link rel="stylesheet" href="../../static/style.css">
думаю тут тоже лучше через url_for подтягивать статику, чем через относительные пути

2022-06-18 16:33 UTC, painassasin commented on loader/templates/post_form.html
> +    <a href="{{ url_for('main_blueprint.page_index') }}" class="link">Назад</a>
Кнопка должна называться "На главную страницу", либо у тебя не правильно указана ссылка)

Назад - означает "на предыдущую страницу". Данную страницу можно получить из объекта request, есть такое свойство/заголовок, которое проставляет браузер, называется referrer

2022-06-18 16:33 UTC, painassasin commented on loader/views.py
> +        post = Post(picture, text)
А если пользователь картинку не прикрепил? Тут все пойдет на перекосят, поэтому проверь для начала наличие картинки и если ее нет - верни 400 с соответствующим сообщением

2022-06-18 16:33 UTC, painassasin commented on loader/views.py
> +            picture_path = f"/uploads/images/{picture_name}"
Честно говоря не очень нравится, что у тебя все пути указаны "сырыми строками". Я бы объявил их где-нибудь в настройках и использовал тут и выше в репозитории склейки.

2022-06-18 16:33 UTC, painassasin commented on classes.py
> +    def save_picture(self):
Вообще это немного нарушает принцип единой ответственности, но думаю в данной программе это допустимо, но на будущее знай, что у тебя класс И работает с параметрами (изменяет, валидирует, и прочее) но также и с файлом работает. Поэтому, если завтра мы будем хранить посты в базе, придется править этот класс, что не очень хорошо. Но как я сказал, в данном случае в виду маленькой программы это не критично

2022-06-18 16:33 UTC, painassasin commented on loader/views.py
> +            return redirect(url_for('.post_uploaded'))
Тут точно точка нужна?

2022-06-18 16:33 UTC, painassasin commented on loader/views.py
> +            flash('Не верный формат файла изображения. Используйте JPG, PNG', 'warning')
Отлично, что используешь `flash` и научился работать с сообщениями

2022-06-18 16:33 UTC, painassasin commented on main.log
> +2022-06-17T20:36:10.269106+0700 INFO Запрос в базе не найден
Файл нужно добавить в .gitignore
Как собственно и __pycache__ некоторые (в loader_bp, main_bp)

2022-06-19 06:20 UTC, VladmimirShtefan commented on app.py
> +app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or 'SuperSecretKey'
У меня в настройках flask server в Environment variables SECRET_KEY=SuperKey. Вроде все правильно.

2022-06-19 10:04 UTC, VladmimirShtefan commented on loader/views.py
> +        post = Post(picture, text)
Ну тут не пойдет на перекосяк, сработает исключение и появится ошибка что не тот формат файла. Думал проверить на тип файла через mimetype чтобы выдавать что фаил не прикреплен, но если его не прикреплять все равно возвращается application/octet-stream и если без расширения фаил прикрепить application/octet-stream. Поэтому мудрил через проверку на имя фаила.

2022-06-19 10:18 UTC, VladmimirShtefan commented on classes.py
> +        file_extension: str = self.picture.filename.split('.')[-1]
Добавил проверку, но через mimetype все равно пропускает переименованные фаилы. Нашел библиотеку magic. Но пока не разобрался как туда сразу подсунуть FileStorage.

2022-06-19 10:19 UTC, VladmimirShtefan commented on loader/views.py
> +            flash('Не верный формат файла изображения. Используйте JPG, PNG', 'warning')
Спасибо)

2022-06-19 10:20 UTC, VladmimirShtefan commented on main.log
> +2022-06-17T20:36:10.269106+0700 INFO Запрос в базе не найден
не пойму, вроде добавил фалы pycache, но git их все равно видит.

2022-06-19 10:59 UTC, VladmimirShtefan commented on loader/templates/post_form.html
> +    <a href="{{ url_for('main_blueprint.page_index') }}" class="link">Назад</a>
Подскажи, не могу понять как сделать чтобы, при добавлении новой статьи, мы переходим к отображению добавленной статьи и при нажатии назад возвращаемся к добавлению статьи (все правильно), но если еще раз назад нажать он помнит что это наша страница с добавленным постом, а должен идти на главную.

2022-06-19 14:23 UTC, painassasin commented on app.py
> +app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or 'SuperSecretKey'
Я не про это, тут оператор or - лишний, у тебя сам синтаксис не верный, вот я к чему

2022-06-19 14:30 UTC, painassasin approved these changes

2022-06-19 14:30 UTC, painassasin commented on classes.py
> +        if file_extension in {'image/jpg', 'image/png'}:
Во-первых, это не extension (расширение)
Во-вторых почему не:
```python
def check_file_extension(self) -> bool:
    return self.picture.mimetype.startswith('image/')
```

2022-06-19 14:30 UTC, painassasin commented on classes.py
> +class Page:
Я думаю в данном случае класс будет лишним, 
достаточно просто добавлять request.refferer при рендеринга шаблона

2022-06-19 14:46 UTC, VladmimirShtefan commented on classes.py
> +        if file_extension in {'image/jpg', 'image/png'}:
потому что нам нужно именно jpg png

2022-06-19 15:04 UTC, VladmimirShtefan commented on app.py
> +app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or 'SuperSecretKey'
Это я написал чтобы если у тебя не выставлен ключ в настройках, то использовать 'SuperSecretKey'

2022-06-19 15:04 UTC, VladmimirShtefan commented on classes.py
> +class Page:
не чувствую еще когда нужен класс когда нет

2022-06-19 15:05 UTC, merged

2022-06-20 06:41 UTC, painassasin commented on app.py
> +app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY') or 'SuperSecretKey'
Как оператор get у словаря так и работает! 
```python
>>> help(dict.get)
get(self, key, default=None, /)
    Return the value for key if key is in the dictionary, else default.

```

2022-06-20 06:57 UTC, painassasin commented on classes.py
> +        file_extension: str = self.picture.filename.split('.')[-1]
Да, прости, ввел в заблуждение - Flask такое не умеет делать, тут нужно писать что-то свое

Предлагаю так же посмотреть вот [эту статью](https://flask-russian-docs.readthedocs.io/ru/latest/patterns/fileuploads.html), обрати внимание на `save_filename`

2022-06-20 06:58 UTC, painassasin commented on loader/templates/post_form.html
> +    <a href="{{ url_for('main_blueprint.page_index') }}" class="link">Назад</a>
Тут уже никак - такой долгой памяти у браузера нет

2022-06-20 06:58 UTC, painassasin commented on main.log
> +2022-06-17T20:36:10.269106+0700 INFO Запрос в базе не найден
Их теперь нужно удалить через `git rm`

2022-06-20 06:58 UTC, painassasin commented on classes.py
> +        if file_extension in {'image/jpg', 'image/png'}:
Согласен